#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ if data.values.is_externaldns_enabled:
#@   data.values.externaldns.domain or assert.fail("data.values.externaldns.domain can not be empty")
#@   data.values.externaldns.wildcard_domain or assert.fail("data.values.externaldns.wildcard_domain can not be empty")
#@ end
