#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def contour_config():
incluster: true
disablePermitInsecure: false
tls:
  fallback-certificate:
    name: fallback-secret-name
    namespace: data.values.namespace
  envoy-client-certificate:
accesslog-format: envoy
#@ if/end data.values.configFileContents.default_http_versions:
default-http-versions: #@ data.values.configFileContents.default_http_versions
#@ end

#@overlay/match by=overlay.subset({"kind":"Service", "metadata": {"name": "envoy"}})
---
metadata:
  annotations:
    #@ if/end data.values.is_externaldns_enabled == True:
    #@overlay/match missing_ok=True
    external-dns.alpha.kubernetes.io/hostname: #@ "*.{}.,*.{}.".format(data.values.externaldns.domain, data.values.externaldns.wildcard_domain)

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "contour"}})
---
data:
  contour.yaml: #@ yaml.encode(contour_config())

#@overlay/match by=overlay.subset({"kind":"CustomResourceDefinition"}),expects="2+"
---
#@overlay/remove
#@overlay/match missing_ok=True
status:

#@overlay/match by=overlay.subset({"kind":"Job"}),expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: "fallback-on-replace"
