#@data/values-schema
---
namespace: projectcontour
create_namespace: true
privileged_clusterrole_name: ""
service:
  #! Type can be LoadBalancer or ClusterIP
  type: LoadBalancer
#! Enablers
is_externaldns_enabled: false
#! Package config
externaldns:
  domain: ""
  wildcard_domain: ""
