---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 1.25.0
            url: quay.io/failk8s/contour-package:1.25.0
        url: quay.io/failk8s/contour-package@sha256:02ea6e66b4a3e9f4032daae6f6a57e711ce9604997602cbb4bafe3019a4601a6
  name: contour.dev.failk8s.com.1.25.0
spec:
  refName: contour.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/contour-package@sha256:02ea6e66b4a3e9f4032daae6f6a57e711ce9604997602cbb4bafe3019a4601a6
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.25.0
